### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by turgeonmaxime**
We don't need to merge it right now, but I thought we could discuss the following points:

1. I'm using numpy.arrays as a convenience for myself, but since there is no complicated matrix operations we could easily change them to some other data type and remove that dependency.

2. To generate random variates, I use the scipy module. Because of the need for a Dirichlet random variable, I need a recent version (>= 0.15.0). If this is too strong a requirement, we could draw from gammas or betas, which are both part of any version of scipy.

3. As it is set-up right now, the MCMC algorithm is called using the default parameters (i.e. thining parameter, length of burn-in period and number of iterations are fixed). Perhaps we should add something to the parser to allow the user to change these parameters.

Let me know what you think.

### CODE REVIEW

**Comment by jwfoley** [comment]
> I'm using numpy.arrays as a convenience for myself, but since there is no complicated matrix operations we could easily change them to some other data type and remove that dependency.

It might be nice to remove the dependency, but during optimization it may become even more important to use Cython objects (since we're already stuck with Cython from pysam), so rather than make the code less convenient now and possibly still have to change it again later, it's probably better to just keep NumPy for now.

> I need a recent version (>= 0.15.0). If this is too strong a requirement, we could draw from gammas or betas, which are both part of any version of scipy.

We already have the same problem with pysam (pip version is up to date but Ubuntu repository version is too old), so I don't think this makes the problem any worse. It might be helpful to implement version checks though.

> Perhaps we should add something to the parser to allow the user to change these parameters.

Definitely.

**Comment by turgeonmaxime** [comment]
I've changed the implementation. 

1. I'm not using scipy at all anymore, but using the numpy random number generator. 

2. Lists are being used now instead of numpy arrays.

3. I'm also removing zeros at the beginning of the computation. It doesn't have an impact on the estimation process, but since there's quite a lot of zeros, it has a tremendous impact on performance.

**Comment by jwfoley** [comment]
Great - it now runs in a reasonable amount of time and gets very similar results to the R package. But not exactly the same:

    > rowSums(uniform)
    ERCC-00009:889 ERCC-00009:890 ERCC-00009:891 ERCC-00009:892 ERCC-00009:893 
                37              5             17              7              1 
    ERCC-00009:894 ERCC-00009:904 ERCC-00009:944 
                 2              1              1 
    > rowSums(raw) * p.true
    ERCC-00009:889 ERCC-00009:890 ERCC-00009:891 ERCC-00009:892 ERCC-00009:893 
         38.373342       5.414261      16.813019       6.717017       1.000000 
    ERCC-00009:894 ERCC-00009:904 ERCC-00009:944 
          1.725803       1.000000       1.000000 

(where `uniform` is from the Python version and `p.true` is from the R version)

It looks like this is due to random variation in the Python output, as I get slightly different counts each time I run it, but the R version seems quite robust. Does the Python version need to run a numerical algorithm for more iterations or something like that?

**Comment by turgeonmaxime** [comment]
I think the R version looks more robust because you're taking the median of
a single quantity, whereas the Python version takes a median for each tag
with non-zero count, then rounds them before taking the sum. If I tweaked
the R algorithm so that it computes the same medians as python, I also get
some variation.

2015-10-12 9:39 GMT-04:00 jwfoley <notifications@github.com>:

**Comment by jwfoley** [comment]
Is there a reason to prefer the way with the multiple medians? Cet. par. it would be nice to minimize the random variation in rerunning the program.

**Comment by turgeonmaxime** [comment]
It's simply a consequence of the change in focus between the two
algorithms. Recall that in the R package, we were interested in estimating
the proportion of non-duplicates. In the Python implementation, we are
interested in the same proportion, but for each tag.

However, now that we are estimating up to 1,000 parameters, we should
probably increase the default number of iterations. But this can wait until
after the optimisation phase is over, I think.

2015-10-12 10:18 GMT-04:00 jwfoley <notifications@github.com>:

**Comment by jwfoley** [comment]
Do I understand correctly that the difference is the R version estimates the "true" sum of all UMI hit counts, while the Python version estimates the true hit count for each UMI separately?

If so, although we do need the latter numbers in order to choose which reads to mark as duplicates, I think it would still make more sense to estimate the sum first and then distribute the appropriate number of duplicates across all the UMIs, according to some rule that keeps the non-duplicate counts proportional to the duplicate counts but also retains at least one hit for each observed UMI. Downstream analysis is just going to look at the sum, so it's more important to get the sum right than work out which specific reads are the true duplicates.

Or maybe these two approaches will converge anyway with more iterations?

**Comment by turgeonmaxime** [comment]
I think that from a methodological perspective, the Python approach makes more sense: we are essentially estimating the "true hit count" using the expected value of the corresponding random variable. I'm not sure that a distributive approach, given the sum of true counts, would have the same theoretical appeal.

With more iterations, each approach will be more stable, but we have to remember that what we are estimating is not really a count, but rather a proportion, and therefore there will always be some rounding up to do. The R version rounds only once, whereas the Python version round multiple times, which explains the discrepancy between the two approaches in how they estimate the sum of true counts. But it seems to me that the difference is negligible.

**Pull request merged**
